apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.21.1-dev+build.12
  name: release-i-027cb-9ea44e5
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.230.0.0/16
    services:
      cidrBlocks:
      - 10.231.100.0/24
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.80.214.106
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: release-i-027cb-9ea44e5-cp
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: CloudStackDatacenterConfig
    name: release-i-027cb-9ea44e5
  eksaVersion: v0.21.1-dev+build.12
  externalEtcdConfiguration:
    count: 1
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: release-i-027cb-9ea44e5-etcd
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.31"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: release-i-027cb-9ea44e5
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: release-i-027cb-9ea44e5
    machineHealthCheck:
      maxUnhealthy: 40%
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackDatacenterConfig
metadata:
  name: release-i-027cb-9ea44e5
  namespace: default
spec:
  availabilityZones:
  - account: ci-admin
    credentialsRef: global
    domain: ROOT
    managementApiEndpoint: http://10.80.25.28:8080/client/api
    name: az-zone1
    zone:
      name: Zone1
      network:
        name: eksa-cloudstack-ci-net

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: release-i-027cb-9ea44e5-cp
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: kubernetes-1-31-eks-6-redhat-9
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  name: release-i-027cb-9ea44e5
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: kubernetes-1-31-eks-6-redhat-9
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: release-i-027cb-9ea44e5-etcd
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: kubernetes-1-31-eks-6-redhat-9
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-cloudstack-release-0-21-ebe3d0b5-2da0-41d1-822a-77758d0a32c7-80
  clusterConfigPath: aws-eks-anywhere-test-cloudstack-release-0-21-ebe3d0b5-2da0-41d1-822a-77758d0a32c7-80
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-cloudstack-release-0-21-ebe3d0b5-2da0-41d1-822a-77758d0a32c7-80.git
  systemNamespace: default

---
